drv/AVLTreeSet.drv, drv/RBTreeSet.drv
Obvious typo s/keysclass/keyclass/ + getter does not exist, but is also not needed.
=> Fix get() in Red-Black and AVL trees.

drv/AVLTreeMap.drv, drv/RBTreeMap.drv, test/it/unimi/dsi/fastutil/objects/ObjectAVLTreeSetTest.java, test/it/unimi/dsi/fastutil/objects/ObjectRBTreeSetTest.java
POC commit for addTo() functionality for Ring class AVLTrees: it passes the test.sh for all AVLTreeMaps and I have added a testAddTo() method in the affected classes. (Note that ObjectHeapPriorityQueue seems to be failing for unrelated reasons)
I also introduced IS_RING in the c-preprocessor in order to make the code a little cleaner. If this looks good I'll extend this to RB trees and any other tree based map :smiley: 
The improvements in speed on benchmarks show about a 2x speedup if there are many operations that use addTo() in place of get()/put() [see this discussion](https://groups.google.com/forum/#!topic/fastutil/H5JoiL0tFh4).
-Almog
=> introduce addTo() to Ring class AVLTrees

drv/AVLTreeMap.drv, drv/AVLTreeSet.drv, drv/AbstractBigList.drv, drv/AbstractFunction.drv, drv/AbstractIterator.drv, drv/AbstractList.drv, drv/AbstractMap.drv, drv/AbstractPriorityQueue.drv, drv/AbstractSortedMap.drv, drv/AbstractSortedSet.drv, drv/BigListIterators.drv, drv/BigLists.drv, drv/Functions.drv, drv/Iterators.drv, drv/Map.drv, drv/Maps.drv, drv/OpenHashMap.drv, drv/RBTreeMap.drv, drv/RBTreeSet.drv, drv/SortedMaps.drv, drv/SortedSets.drv
This patch adds @Deprecated warnings to various methods, where a non-boxed alternative exists.
This is useful for finding such locations in user code to improve the code, e.g. if getIntKey() exists, then getKey() will be deprecated and cause a warning.
Conditionals are in place to not deprecate methods for non-primitives.
=> Add @Deprecated warnings to methods with better alternatives

drv/OpenHashBigSet.drv, drv/OpenHashSet.drv, test/it/unimi/dsi/fastutil/objects/ObjectOpenHashBigSetTest.java, test/it/unimi/dsi/fastutil/objects/ObjectOpenHashSetTest.java
Works like add(k) followed by get(k), but is cheaper.
This is useful for managing unique objects, e.g.
ObjectHashSet<String> unique;
key = unique.addOrGet(key);
I have wrapped this code in "#if #keyclass(Object)", because for primitives it is equivalent to "add(k); return k;".
For hash sets, the code duplication isn't too bad. But for the tree-based sets it is massive, so I didn't do these.
Again, untested code, sorry. Consider this to be a feature request.
=> Add addOrGet(k) to ObjectHashSets.

test/it/unimi/dsi/fastutil/ints/Int2IntLinkedOpenHashMapTest.java, test/it/unimi/dsi/fastutil/ints/IntLinkedOpenHashSetTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1854 - “ Dead stores should be removed ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1854
Please let me know if you have any questions.
Ayman Abdelghany.
=> Dead stores should be removed

test/it/unimi/dsi/fastutil/doubles/DoubleBigArraysTest.java, test/it/unimi/dsi/fastutil/ints/IntBigArraysTest.java, test/it/unimi/dsi/fastutil/objects/ObjectBigArraysTest.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2131 - “Primitives should not be boxed just for "String" conversion”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S2131
Please let me know if you have any questions.
Ayman Abdelghany.
=>  Primitives should not be boxed just for "String" conversion

drv/Iterator.drv, gencsource.sh
Type-specific iterators now extend the primitive iterators of the JDK if available.
Closes #43
=> Extend primitive iterators of the JDK

src/overview.html
This fixes a couple minor typos in overview.html.
=> overview.html: fix a couple typos

drv/Comparator.drv, drv/Comparators.drv
Only one overload of thenComparing() is overridden. The others that take
functions that do a key extraction will require more code gen (possibly more then it is worth).
=> Override reversed() and thenComparing() for primitive Comparators

drv/Arrays.drv
It was intended that longs and doubles had the greatest radix sort
threshold, but it got swapped with ints' thresholds accidentally.
=> Fix any issue where longs were using a smaller radix sort threshold

src/it/unimi/dsi/fastutil/SafeMath.java
MIN_VALUE is actually the positive closest-to-zero value that a float can represent. So this function would break on 0 and negative float values.
=> Fix SafeMath#safeDoubleToFloat for values <= 0

drv/AbstractCollection.drv, drv/AbstractList.drv, drv/AbstractSet.drv, test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java, test/it/unimi/dsi/fastutil/ints/IntOpenHashSetTest.java
Update object based, boxing bulk operation methods to use the fast type-specific version if possible.
AbstractCollection.addAll
.containsAll
.removeAll
.retainAll
AbstractList.addAll(int, Collection)
AbstractSet.equals
Will now delegate to the fast, type-specific method if given an type-specific collection as their input.
This is a slight behavior change. If there are any user subclasses of AbstractCollection/AbstractList that have implemented their type specific bulk methods as calling the object based ones (despite that being strongly dis-recommended) without overriding the boxed versions being overridden too, this will now cause an infinite recursion.
=> Update object based bulk operation methods to use type specific

drv/ArrayList.drv, drv/ArraySet.drv, drv/List.drv, drv/OpenHashSet.drv, drv/Set.drv, drv/Sets.drv, test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java, test/it/unimi/dsi/fastutil/ints/IntArraySetTest.java, test/it/unimi/dsi/fastutil/ints/IntListTest.java, test/it/unimi/dsi/fastutil/ints/IntOpenHashSetTest.java, test/it/unimi/dsi/fastutil/ints/IntSetTest.java, test/it/unimi/dsi/fastutil/objects/ObjectArrayListTest.java, test/it/unimi/dsi/fastutil/objects/ObjectArraySetTest.java, test/it/unimi/dsi/fastutil/objects/ObjectListTest.java, test/it/unimi/dsi/fastutil/objects/ObjectOpenHashSetTest.java, test/it/unimi/dsi/fastutil/objects/ObjectSetTest.java
Clean up the of methods()
- Make the `of` methods in the root `List` and `Set` interfaces return immutable collections (like the platform does)
- Validate that duplicate entries to the "of" method of sets throws (like the platform does)
Because of this validation, it is now worth it to have overloads of 0 and 1 element, which skip the temporary array and validation (0 and 1 element sets can never have duplication).
In the spirit of ArraySet's "just trust me" API of working raw arrays unvalidated, an it has an offshoot `ofUnchecked` that takes the elements as is and does no validation, like the array accepting constructors do.
=> Clean up some of the new "of()" static factory methods.

drv/BigList.drv, src/overview.html
* Fix BigList's default setElements function using the size of the outer array instead of the proper BigArrays.length.
* Add an example of intStream usage to overview.html
* Update overview.html examples to show off the new of static factory methods.
=> Some minor fixes and additions

drv/ArrayList.drv, drv/ImmutableList.drv, test/it/unimi/dsi/fastutil/objects/ObjectArrayListTest.java
Harden immutability of ImmutableList.
This closes a few avenues that could have lead to mutating the supposed to be immutable list. In particular, the backing array was non-final and protected (now private and final), and mutations could still happen through the iterator.
Adds the cult-favorite optimization of sharing a single empty instance if given empty arguments to the static constructor.
Also add fast toArray for object based ImmutableList and ArrayList.
=> Harden immutability of ImmutableList.

drv/BigList.drv, drv/IndirectPriorityQueue.drv, drv/Iterable.drv, drv/List.drv, drv/Map.drv, drv/PriorityQueue.drv, drv/Set.drv, drv/SortedMap.drv, drv/SortedSet.drv, drv/Spliterator.drv
Also, one unrelated change to List.sort it wouldn't always mention that `null` comparator means natural order for the Object based Lists.
=> Add some @apiNotes to places they should have been.

drv/Spliterators.drv, test/it/unimi/dsi/fastutil/ints/IntSpliteratorsTest.java
Fixes https://github.com/vigna/fastutil/issues/190
Given the niche use of Spliterators.concat, I would be fine with this going into a 8.5.1 and not hold up the 8.5.0 release for it.
=> Fix concat'ed spliterators reporting SORTED or DISTINCT when not safe

CHANGES, drv/AbstractCollection.drv, drv/Collection.drv, drv/Collections.drv, drv/Iterators.drv, drv/Lists.drv, drv/Predicate.drv, drv/Sets.drv, gencsource.sh, test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java, test/it/unimi/dsi/fastutil/objects/ObjectArrayListTest.java, test/it/unimi/dsi/fastutil/shorts/ShortArrayListTest.java
The `removeIf` method had an ambiguity if you tried to use it with lambdas, requiring you to cast to a functor type yourself.
This change fixes it so it chooses a proper primitive Predicate.
It basically applies what was done to `forEach` and `forEachRemaining` to `removeIf`.
=> Fix removeIf ambiguity

drv/ImmutableList.drv, drv/List.drv
If we don't even do it for ImmutableList.of(...), there is no point in the root List interface to doing it.
=> Don't have List.of(...) make a defensive copy.

drv/ArrayList.drv, drv/Collection.drv, drv/Iterable.drv, drv/Iterator.drv, drv/Iterators.drv, drv/Spliterators.drv
Some more conditional fixups and simplifications, especially taking advantage of the new `KEY_BYTE_CHAR_SHORT_FLOAT` macro.
=> Simplify conditionals

drv/ArrayList.drv, drv/ImmutableList.drv, drv/OpenHashSet.drv
Per https://github.com/vigna/fastutil/issues/211, the `toXWithExpectedSize` collector methods will preallocate the full size for every worker thread when used on parallel streams.
This is rather wasteful, as most worker threads will not handle the full contents of the stream.
Actually solving this shortcoming may come in future work, but for now we just warn about it in an `@implNote`
=> Warn about preallocation collectors and parallel streams

drv/Predicate.drv, drv/UnaryOperator.drv
Adds the static method `identity` to UnaryOperator
For numeric primitives, adds `negation`, performing arithmetic negation.
For `BooleanUnaryOperator`, adds `negation`, performing logical negation.
For `BooleanPredicate`, it also adds those methods, as it also takes a boolean and returns a boolean, thus they make sense there too.
=> Add identity() to UnaryOperator

drv/Iterators.drv, drv/List.drv, drv/Spliterators.drv, gencsource.sh
Minor touchups.
* Add Javadoc to Iterators.any/all/indexOf and Spliterators.forEachMatching
* Undeprecate the JDK primitive overloads of any/all/indexOf. Now the overhead is documented as an `@implNote` to conform to the other similar methods in fastutil.
* Make an overload of `Spliterators.forEachMatching` that accept the JDK primitive operators.
* Make `List.replaceAll(JDK_PRIMITIVE_UNARY_OPERATOR)` forward to `List.replaceAll(KEY_UNARY_OPERATOR)` if possible, because, for example, `ByteUnaryOperator` is a subinterface of `java.util.function.IntUnaryOperator`.
* Convert iterator accepting methods of `Iterators` that don't need the fastutil specific methods to use `STD_KEY_ITERATOR`, which allows the regular `java.util.Iterator` to be accepted for the `ObjectIterators` class.
* Convert …
=> Minor touchups

drv/AbstractBigList.drv, drv/AbstractList.drv
AbstractList gives a mostly effecient spliterator for RandomAccess subclasses.
While subclasses can certainly do better by abusing internals, this one
won't display the terrible splitting performance that the Iterator based one
from the root List interface does.
We should document this fact (and make it an assurance) so subclassers don't
feel obligated to write their own Spliterator to not get terrible parallel
performance.
Also make the spliterator late-binding, bringing them into line with the default implementations in the List and BigList classes.
Same for AbstractBigList.
=> Document effecient spliterator for a RandomAccess AbstractList

drv/AbstractBigList.drv, drv/AbstractList.drv, drv/BigList.drv, drv/Collection.drv, drv/List.drv, drv/Set.drv, drv/SortedSet.drv
Also pull the RandomAccess check for the default implementation of
spliterator() from AbstractList into List, to match up with what java.util.List does.
The detail is rather excruciating, but spliterator is kind of a nuanced API like that requiring that level of detail, at least in the interfaces it does.
=> Further document the spliterator methods in interfaces.

drv/AVLTreeMap.drv, drv/AbstractBigList.drv, drv/AbstractList.drv, drv/ArrayList.drv, drv/BigArrayBigList.drv, drv/BigList.drv, drv/BigLists.drv, drv/Collection.drv, drv/ImmutableList.drv, drv/ImmutablePair.drv, drv/ImmutableSortedPair.drv, drv/List.drv, drv/Lists.drv, drv/Map.drv, drv/MutablePair.drv, drv/OpenHashBigSet.drv, drv/OpenHashMap.drv, drv/OpenHashSet.drv, drv/RBTreeMap.drv, drv/Set.drv, drv/Sets.drv, drv/SortedMaps.drv, drv/SortedSets.drv, gencsource.sh
This is much clearer that we mean the types that use `==` for equality testing instead of `.equals`, and not confuse it with the `KEYS_REFERENCE` macro which means any types using Object backed members.
Also documents the gotcha of trying to use a Reference based and a non-Reference based collection together (e.g. you may get non symmetric `equals`)
Also does the same for VALUE.
=> Replace KEY_CLASS_Reference with KEYS_USE_REFERENCE_EQUALITY

drv/ImmutableList.drv, test/it/unimi/dsi/fastutil/ints/IntImmutableListTest.java
Would happen to return `true` if any ImmutableList was given, equal contents or not.
=> Fix a rather critical bug where ImmutableList.equals would return true erroneosly

drv/ArrayList.drv, drv/ImmutableList.drv, drv/Lists.drv, test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java, test/it/unimi/dsi/fastutil/ints/IntImmutableListTest.java
Add a fast `subList` for `ImmutableList`.
Currently `ImmutableList.subList` doesn't return an `ImmutableList` itself due to the current implementation of `ImmutableList` being closely tied to the idea the full array is the whole list. This may change in a future release.
Fixes https://github.com/vigna/fastutil/issues/223
Also applies some of the optimizations conceived for `ImmutableList.subList` to `ArrayList.subList`
=> Sub list for immutable list

drv/ArrayList.drv, drv/BigArrayBigList.drv
Instead of newly creating an empty big array, now it fallsback to the default constructor.
This will allow it to have much better resizing performance, as instead of 0->1 on first add, it will go 0->10 (because of `DEFAULT_EMPTY_BIG_ARRAY` being used now).
The array based `of` remains the same; we need to ensure the same runtime type is kept, even if empty.
Also minor doc updates to `ArrayList` as well.
=> Add a faster case if BigArrayBigList.of() (no arguments) is called.

drv/AbstractMap.drv, drv/Map.drv, drv/Maps.drv, drv/OpenHashMap.drv, test/it/unimi/dsi/fastutil/ints/Int2IntMapGenericLinkedOpenHashTest.java, test/it/unimi/dsi/fastutil/ints/Int2IntMapGenericTest.java, test/it/unimi/dsi/fastutil/ints/Int2ObjectMapGenericLinkedOpenHashTest.java, test/it/unimi/dsi/fastutil/ints/Int2ObjectMapGenericTest.java
* Fix issues where not all the ways to iterate `keySet` or `values` in a LinkedOpenHashMap would follow the proper order (instead falling back to regular OpenHashMap order).
* Make sure all OpenHashMap's (and their Linked and Custom cousins) views have proper iterators and spliterators, as well as proper `forEachRemaining` methods. This saves a lot of implicit casts by the generics supporting bridge methods the compiler inserts.
* Add unit tests for these
* Give some views of AbstractMap better `spliterator()` methods
=> Fix issues with Map view iterators and spliterators

drv/AbstractMap.drv, test/it/unimi/dsi/fastutil/ints/AbstractInt2IntMapTest.java
If both the default `containsValue` and the default `values` methods are
inherited by an implementating class, they will get a `StackOverflowError`
on trying to test for a value being present.
This is because the default `values().contains` calls `containsValue`, but
the default `containsValue` calls `values().contains`.
Now make the default `containsValues` loop over the entry set.
Add a comment that you should probably override this is your `values()`
has a better implementation. Same also retroactively applied to `containsKey`
and `keySet()`.
Finally, retrofits `AbstractInt2IntMapTest` to extend`Int2IntMapGenericTest`, with a dummy testonly implementation that implements the bare minimum for a mutable Int2Int map. This is to test as many of the `AbstractInt2IntMap`'s default methods as …
=> Fix AbstractMap containing a stack overflow containsValue

drv/ArrayList.drv, drv/Collections.drv, drv/ImmutableList.drv, drv/OpenHashSet.drv, test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java, test/it/unimi/dsi/fastutil/ints/IntImmutableListTest.java, test/it/unimi/dsi/fastutil/ints/IntOpenHashSetTest.java, test/it/unimi/dsi/fastutil/objects/ObjectArrayListTest.java, test/it/unimi/dsi/fastutil/objects/ObjectOpenHashSetTest.java
Fix toXWithExpected size overallocating in parallel stream.
This is accomplished by having the `Supplier` preallocate a `Collection`
of full expected size for the first collection allocation in the first thread,
1/2 expected size for the second, 1/3 for the third, etc.
Fixes #211
This reduces the minimum _memory_ allocated when using this in a parallel stream from
Ω(threads \* expectedSize) -> Ω(threads \* H_expectedSize) = Ω(threads \* ln(expectedSize)).
(The worst case memory usage is still O(threads \* expectedSize), but that requires some truly pathological splitting decisions by the backing `Spliterator`, and is a problem the non-sizing logic would have too)
Where Ω is the min asymptotically bounding function (Think O notation but for the min instead of max)
threads is the number of …
=> Fix toXWithExpected size overallocating in parallel stream.

src/it/unimi/dsi/fastutil/io/FastBufferedOutputStream.java, test/it/unimi/dsi/fastutil/io/FastBufferedOutputStreamTest.java
If the output is closed before `FastBufferedOutputStream` is closed, then `close()` would throw because `close()` calls `flush()`, and it would try to write the buffer, even if there's nothing to write, and zero-length `write()` on a closed stream throws in some `OutputStream` implementations.
This can happen if the output is a socket, for example, that is managed separately from the output stream.
Fix by not calling `write()` from `flush()` at all if there is nothing to write.
If the buffer is not empty, then it would still try to write it, and would throw, which is probably correct.
=> Fix FastBufferedOutputStream.close() exception

drv/HeapIndirectPriorityQueue.drv
Hi!
It looks like the work is already done in super constructor
=> Removed excessive init in HeapIndirectPriorityQueue constructor

drv/ImmutableList.drv, test/it/unimi/dsi/fastutil/ints/IntImmutableListTest.java
listIterator() on a sublist needs to correct its index to add "from" to it.
=> Fix bug in ImmutableSubList iterator

drv/SortedSets.drv
Here a quite anoyed small bugfix.
=> `TypeSortedSets.emptySet()` should return `SortedSet`

drv/ArrayList.drv
The current implementation of ArrayList.iterator().back(int n) compute the number of remaining elements wrongly.
It compute `size-pos`, which is correct for the skip(int n) method, but wrong for the back(int n) method.
=> ArrayList iterator back() bug fix, compute remaining correctly

drv/ImmutableList.drv
ensureRestrictedIndex in abstract list compare to size(), 'from' should not be used.
=> Immutable sub list iterator bug fix, ensureIndex is relative to sub range

drv/ImmutableList.drv, test/it/unimi/dsi/fastutil/ints/IntArrayListTest.java, test/it/unimi/dsi/fastutil/ints/IntImmutableListTest.java
\*ImmutableList for primitives can produce an ArrayIndexOutOfBoundsException via System.arraycopy due to using `a.length` rather than `this.a.length` or `size()` within context of the parameter being named `a` as well.
This also introduces testcases in IntImmutableListTest and IntArrayListTest to ensure that the check does not regress.
=> Fix error passing oversized array to PrimitiveImmutableList

drv/ArrayList.drv
In the previous pull request (#311), I optimized the array field access of some classes. Recently, with my deeper understanding of fastutil, I have discovered more optimizations and technical debts that need attention. However, resolving these issues is challenging and time-consuming, requiring contributions from the community and multiple pull requests. This pull request is the recent work I have done on ArrayList.
=> Optimize ArrayList

drv/Comparator.drv, test/it/unimi/dsi/fastutil/ints/IntComparatorTest.java
https://github.com/vigna/fastutil/issues/312
=> Primitive Comparator.comparing(keyExtractor), like standrad Comparator

drv/OpenHashMap.drv, test/it/unimi/dsi/fastutil/objects/Object2IntOpenHashMapTest.java
The `#if VALUES_PRIMITIVE && ! VALUE_CLASS_Boolean` comes from the superclass in Map.drv: https://github.com/vigna/fastutil/blob/355d8ebfaf2bcc4032cc1c25bec9f3fe827f8175/drv/Map.drv#L649
The implementation mostly is copied from the method below (`merge`), with dead code removed because `VALUES_PRIMITIVE` is always true.
I'm using the `METHOD_ARG_VALUE_BINARY_OPERATOR` so that we prefer using the JDK ${Primitive}BinaryOperator classes, and fall back to the fastutil primitive-BinaryOperators where not present in the JDK.
I ran the junit tests locally and they pass.
Towards #336
=> OpenHashMaps.mergePRIMITIVE: Avoid double-hashing key

.gitignore, src/it/unimi/dsi/fastutil/io/FastByteArrayOutputStream.java
1) copyright 2024→2025
2) toByteArray similar to ByteArrayOutputStream#toByteArray() for easy migration and daily life
3) super class close() and write(byte[]) repeated without IOException
=> FastByteArrayOutputStream: Small Usability improvement 

drv/Map.drv, test/it/unimi/dsi/fastutil/objects/Object2ObjectMapTest.java
Pretty simple PR, I think
Things to note:
- Java doc is a bit quaint because I thought it was useless to copy paste the original methods
- an `entry(key, value)` static method was also added to make it easier to use, just like `java.util.Map`
- I did not include `Int2IntMapTest` because I would have put the same things I did in `Object2ObjectMapTest`
- More tests could probably be added but I have no idea what they could be
Close #329
=> Add ofEntries static method to Map interfaces
